insert into addresses (id, country_iso, city, street, postcode) values (1, 'MW', 'Nkhotakota', '01524 Spaight Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (2, 'RS', 'Taraš', '31917 Maple Wood Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (3, 'PT', 'Fortios', '0 Schlimgen Park', '7300-655');
insert into addresses (id, country_iso, city, street, postcode) values (4, 'RU', 'Khasavyurt', '70061 Sachtjen Hill', '368044');
insert into addresses (id, country_iso, city, street, postcode) values (5, 'CZ', 'Palkovice', '64 Schlimgen Circle', '739 41');
insert into addresses (id, country_iso, city, street, postcode) values (6, 'ID', 'Beaung Tengah', '69 Acker Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (7, 'AF', 'Kushk', '85 Sunnyside Road', null);
insert into addresses (id, country_iso, city, street, postcode) values (8, 'PL', 'Siewierz', '69144 Colorado Center', '42-470');
insert into addresses (id, country_iso, city, street, postcode) values (9, 'RU', 'Sandovo', '9404 Mariners Cove Trail', '171750');
insert into addresses (id, country_iso, city, street, postcode) values (10, 'AM', 'Noyemberyan', '6859 Colorado Place', null);
insert into addresses (id, country_iso, city, street, postcode) values (11, 'BR', 'Piraí', '979 Old Shore Drive', '27175-000');
insert into addresses (id, country_iso, city, street, postcode) values (12, 'CN', 'Luzhou', '7867 Vidon Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (13, 'ID', 'Suru', '10696 Stoughton Pass', null);
insert into addresses (id, country_iso, city, street, postcode) values (14, 'PH', 'Viejo Daan Banua', '4357 Northridge Alley', '6119');
insert into addresses (id, country_iso, city, street, postcode) values (15, 'RU', 'Atlasovo', '5840 Lyons Lane', '901095');
insert into addresses (id, country_iso, city, street, postcode) values (16, 'PF', 'Afareaitu', '91 Valley Edge Junction', null);
insert into addresses (id, country_iso, city, street, postcode) values (17, 'PL', 'Mełgiew', '13888 4th Pass', '21-007');
insert into addresses (id, country_iso, city, street, postcode) values (18, 'US', 'New York City', '88 Ruskin Avenue', '10060');
insert into addresses (id, country_iso, city, street, postcode) values (19, 'EG', 'Bilqās', '741 Wayridge Trail', null);
insert into addresses (id, country_iso, city, street, postcode) values (20, 'NL', 'Utrecht (stad)', '477 Bayside Terrace', '3550');
insert into addresses (id, country_iso, city, street, postcode) values (21, 'US', 'Montgomery', '552 Acker Street', '36177');
insert into addresses (id, country_iso, city, street, postcode) values (22, 'US', 'Waco', '332 Kenwood Crossing', '76796');
insert into addresses (id, country_iso, city, street, postcode) values (23, 'PH', 'Iba', '06498 Shelley Way', '2201');
insert into addresses (id, country_iso, city, street, postcode) values (24, 'RS', 'Boljevci', '57843 8th Trail', null);
insert into addresses (id, country_iso, city, street, postcode) values (25, 'CO', 'Palmito', '638 Anthes Road', '706037');
insert into addresses (id, country_iso, city, street, postcode) values (26, 'JP', 'Funehikimachi-funehiki', '95027 Beilfuss Plaza', '963-4603');
insert into addresses (id, country_iso, city, street, postcode) values (27, 'CN', 'Huadian', '1754 Gerald Park', null);
insert into addresses (id, country_iso, city, street, postcode) values (28, 'PH', 'Bagay', '42 Buhler Alley', '1697');
insert into addresses (id, country_iso, city, street, postcode) values (29, 'RU', 'Krasnoznamensk', '74021 Mifflin Street', '172126');
insert into addresses (id, country_iso, city, street, postcode) values (30, 'PL', 'Bęczarka', '28 Calypso Pass', '32-445');
insert into addresses (id, country_iso, city, street, postcode) values (31, 'SE', 'Boxholm', '724 Stephen Lane', '590 14');
insert into addresses (id, country_iso, city, street, postcode) values (32, 'SE', 'Borås', '9513 Corry Parkway', '506 40');
insert into addresses (id, country_iso, city, street, postcode) values (33, 'PL', 'Łomża', '60 West Alley', '18-404');
insert into addresses (id, country_iso, city, street, postcode) values (34, 'GR', 'Lykóvrysi', '056 Arizona Crossing', null);
insert into addresses (id, country_iso, city, street, postcode) values (35, 'ID', 'Waiwukak', '99830 Maple Wood Lane', null);
insert into addresses (id, country_iso, city, street, postcode) values (36, 'UA', 'Korolevo', '030 Jenifer Place', null);
insert into addresses (id, country_iso, city, street, postcode) values (37, 'ID', 'Gunem', '48763 Summer Ridge Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (38, 'RU', 'Segezha', '70 Tennessee Road', '186424');
insert into addresses (id, country_iso, city, street, postcode) values (39, 'RU', 'Sol’tsy', '3 Hanover Place', '175040');
insert into addresses (id, country_iso, city, street, postcode) values (40, 'LT', 'Obeliai', '6 Vidon Court', '42006');
insert into addresses (id, country_iso, city, street, postcode) values (41, 'IR', 'Kavār', '7 Blaine Pass', null);
insert into addresses (id, country_iso, city, street, postcode) values (42, 'CN', 'Zhenwen', '7 Forster Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (43, 'RU', 'Shalazhi', '50 Kings Court', '366526');
insert into addresses (id, country_iso, city, street, postcode) values (44, 'PH', 'Mauhao', '90 Stone Corner Plaza', '5214');
insert into addresses (id, country_iso, city, street, postcode) values (45, 'MX', 'Benito Juarez', '439 New Castle Hill', '35180');
insert into addresses (id, country_iso, city, street, postcode) values (46, 'GE', 'Tsinandali', '80 Kenwood Circle', null);
insert into addresses (id, country_iso, city, street, postcode) values (47, 'PL', 'Kolbuszowa', '14 Basil Plaza', '36-100');
insert into addresses (id, country_iso, city, street, postcode) values (48, 'NL', 'Bergen op Zoom', '646 Heath Terrace', '4619');
insert into addresses (id, country_iso, city, street, postcode) values (49, 'UG', 'Ntungamo', '77323 Bluestem Avenue', null);
insert into addresses (id, country_iso, city, street, postcode) values (50, 'RU', 'Khasavyurt', '7868 Delaware Parkway', '368044');
insert into addresses (id, country_iso, city, street, postcode) values (51, 'AR', 'Embarcación', '0870 Sullivan Street', '4550');
insert into addresses (id, country_iso, city, street, postcode) values (52, 'PH', 'Tairan Camp', '14 Chive Way', '7301');
insert into addresses (id, country_iso, city, street, postcode) values (53, 'CN', 'Longcun', '44 Rigney Avenue', null);
insert into addresses (id, country_iso, city, street, postcode) values (54, 'SD', 'Port Sudan', '9 Reinke Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (55, 'CN', 'Leluo', '27 Daystar Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (56, 'CN', 'Jiamiao', '954 Gerald Terrace', null);
insert into addresses (id, country_iso, city, street, postcode) values (57, 'RU', 'Bolkhov', '8 Pond Place', '303158');
insert into addresses (id, country_iso, city, street, postcode) values (58, 'VE', 'Ocumare del Tuy', '12 Farragut Parkway', null);
insert into addresses (id, country_iso, city, street, postcode) values (59, 'ID', 'Bangus Kulon', '857 Truax Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (60, 'OM', 'Barkā’', '36009 Scoville Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (61, 'PT', 'Venda', '406 Artisan Lane', '4715-529');
insert into addresses (id, country_iso, city, street, postcode) values (62, 'CN', 'Qiaonan', '79 Aberg Parkway', null);
insert into addresses (id, country_iso, city, street, postcode) values (63, 'MK', 'Крушопек', '84834 Lillian Crossing', '1040');
insert into addresses (id, country_iso, city, street, postcode) values (64, 'FR', 'Mayenne', '1902 Jay Trail', '53104 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (65, 'CN', 'Liudaogou', '17334 Carioca Terrace', null);
insert into addresses (id, country_iso, city, street, postcode) values (66, 'IE', 'Kinnegad', '29085 Pepper Wood Trail', 'R32');
insert into addresses (id, country_iso, city, street, postcode) values (67, 'SY', 'Al Ghandūrah', '33246 Shopko Pass', null);
insert into addresses (id, country_iso, city, street, postcode) values (68, 'RU', 'Temirgoyevskaya', '64106 Butterfield Crossing', '352403');
insert into addresses (id, country_iso, city, street, postcode) values (69, 'NO', 'Elverum', '40821 Esker Way', '2418');
insert into addresses (id, country_iso, city, street, postcode) values (70, 'PT', 'Charneca', '7539 Elka Drive', '2750-524');
insert into addresses (id, country_iso, city, street, postcode) values (71, 'AR', 'El Aguilar', '60 Sunnyside Road', '4634');
insert into addresses (id, country_iso, city, street, postcode) values (72, 'CN', 'Qianguo', '9182 Wayridge Drive', null);
insert into addresses (id, country_iso, city, street, postcode) values (73, 'ID', 'Purut', '4500 Buell Road', null);
insert into addresses (id, country_iso, city, street, postcode) values (74, 'CN', 'Dahe', '17563 Kennedy Junction', null);
insert into addresses (id, country_iso, city, street, postcode) values (75, 'IR', 'Mākū', '34 Fulton Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (76, 'SE', 'Örnsköldsvik', '244 Rutledge Road', '891 41');
insert into addresses (id, country_iso, city, street, postcode) values (77, 'ID', 'Purwasari', '710 Banding Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (78, 'ID', 'Suwaru', '77036 Ludington Court', null);
insert into addresses (id, country_iso, city, street, postcode) values (79, 'PE', 'Huayllati', '459 Jay Parkway', null);
insert into addresses (id, country_iso, city, street, postcode) values (80, 'CN', 'Shunhe', '41601 Jackson Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (81, 'JP', 'Shimada', '9 Farwell Alley', '999-7754');
insert into addresses (id, country_iso, city, street, postcode) values (82, 'SE', 'Valbo', '132 Monument Avenue', '818 31');
insert into addresses (id, country_iso, city, street, postcode) values (83, 'CN', 'Longping', '176 Summerview Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (84, 'ET', 'Āwash', '316 Pepper Wood Parkway', null);
insert into addresses (id, country_iso, city, street, postcode) values (85, 'PH', 'Talangnan', '0725 Dakota Alley', '6028');
insert into addresses (id, country_iso, city, street, postcode) values (86, 'PL', 'Rzozów', '1 Cottonwood Park', '32-060');
insert into addresses (id, country_iso, city, street, postcode) values (87, 'PK', 'Choa Saidān Shāh', '1589 Dwight Road', '53401');
insert into addresses (id, country_iso, city, street, postcode) values (88, 'RU', 'Ust’-Koksa', '53658 Eliot Avenue', '649490');
insert into addresses (id, country_iso, city, street, postcode) values (89, 'CN', 'Wenfu', '14879 Acker Road', null);
insert into addresses (id, country_iso, city, street, postcode) values (90, 'FI', 'Kuhmalahti', '86 Haas Drive', '36810');
insert into addresses (id, country_iso, city, street, postcode) values (91, 'PT', 'Ribeiro', '3777 Old Shore Circle', '4755-578');
insert into addresses (id, country_iso, city, street, postcode) values (92, 'MX', 'Chapultepec', '868 Barnett Trail', '95600');
insert into addresses (id, country_iso, city, street, postcode) values (93, 'ID', 'Binangun', '13 Huxley Circle', null);
insert into addresses (id, country_iso, city, street, postcode) values (94, 'ID', 'Broto', '9582 Burrows Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (95, 'RS', 'Prislonica', '82286 High Crossing Lane', null);
insert into addresses (id, country_iso, city, street, postcode) values (96, 'MX', 'Benito Juarez', '7 Toban Place', '91716');
insert into addresses (id, country_iso, city, street, postcode) values (97, 'MD', 'Soroca', '381 Sycamore Terrace', 'MD-4901');
insert into addresses (id, country_iso, city, street, postcode) values (98, 'BJ', 'Bembèrèkè', '4086 Pawling Drive', null);
insert into addresses (id, country_iso, city, street, postcode) values (99, 'ID', 'Surulangun Rawas', '16 Crowley Parkway', null);
insert into addresses (id, country_iso, city, street, postcode) values (100, 'UA', 'Kuznetsovs’k', '6885 Elgar Center', null);
insert into addresses (id, country_iso, city, street, postcode) values (101, 'PA', 'Chitré', '789 Clarendon Trail', null);
insert into addresses (id, country_iso, city, street, postcode) values (102, 'UA', 'Sumy', '7819 Morning Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (103, 'PT', 'Igreja', '78017 Cambridge Hill', '9200-078');
insert into addresses (id, country_iso, city, street, postcode) values (104, 'CN', 'Zaozhuang', '235 Columbus Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (105, 'RU', 'Roshal’', '9139 Debra Junction', '140732');
insert into addresses (id, country_iso, city, street, postcode) values (106, 'ID', 'Palla', '1 Tennyson Road', null);
insert into addresses (id, country_iso, city, street, postcode) values (107, 'IQ', '‘Afak', '90 High Crossing Hill', null);
insert into addresses (id, country_iso, city, street, postcode) values (108, 'GR', 'Chavárion', '716 Portage Road', null);
insert into addresses (id, country_iso, city, street, postcode) values (109, 'JP', 'Tsuruga', '5 North Alley', '957-0355');
insert into addresses (id, country_iso, city, street, postcode) values (110, 'ZA', 'Bethal', '22 Morning Terrace', '2320');
insert into addresses (id, country_iso, city, street, postcode) values (111, 'PH', 'Dasol', '93699 Mayfield Pass', '2411');
insert into addresses (id, country_iso, city, street, postcode) values (112, 'CN', 'Shunyi', '313 Algoma Lane', null);
insert into addresses (id, country_iso, city, street, postcode) values (113, 'CN', 'Songshu', '08 Manley Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (114, 'CN', 'Yuanshanzi', '02135 Vermont Center', null);
insert into addresses (id, country_iso, city, street, postcode) values (115, 'CN', 'Caotan', '22760 Johnson Court', null);
insert into addresses (id, country_iso, city, street, postcode) values (116, 'PT', 'Quintã', '87613 Westend Crossing', '4620-729');
insert into addresses (id, country_iso, city, street, postcode) values (117, 'ZA', 'Williston', '7428 Pond Junction', '6696');
insert into addresses (id, country_iso, city, street, postcode) values (118, 'CN', 'Jiaotang', '27 Walton Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (119, 'CN', 'Tonggu', '0465 Warbler Trail', null);
insert into addresses (id, country_iso, city, street, postcode) values (120, 'PL', 'Mierzęcice', '89537 Hanover Crossing', '42-460');
insert into addresses (id, country_iso, city, street, postcode) values (121, 'PL', 'Gowarczów', '3 Sloan Point', '26-225');
insert into addresses (id, country_iso, city, street, postcode) values (122, 'GN', 'Mandiana', '352 Boyd Court', null);
insert into addresses (id, country_iso, city, street, postcode) values (123, 'PL', 'Sucha', '4953 La Follette Hill', '89-525');
insert into addresses (id, country_iso, city, street, postcode) values (124, 'PK', 'Shinpokh', '79 Homewood Way', '50001');
insert into addresses (id, country_iso, city, street, postcode) values (125, 'PL', 'Łopuszna', '07 American Trail', '34-432');
insert into addresses (id, country_iso, city, street, postcode) values (126, 'BR', 'Ferraz de Vasconcelos', '155 Cherokee Way', '08500-000');
insert into addresses (id, country_iso, city, street, postcode) values (127, 'CN', 'Jiajiaying', '1 Pierstorff Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (128, 'SE', 'Stockholm', '0 Longview Parkway', '141 99');
insert into addresses (id, country_iso, city, street, postcode) values (129, 'ID', 'Riangbao', '02 Sundown Hill', null);
insert into addresses (id, country_iso, city, street, postcode) values (130, 'BR', 'Rio Novo do Sul', '569 Vidon Plaza', '29290-000');
insert into addresses (id, country_iso, city, street, postcode) values (131, 'PH', 'San Antonio', '48058 Charing Cross Pass', '6407');
insert into addresses (id, country_iso, city, street, postcode) values (132, 'AR', 'Lanús', '601 Gulseth Hill', '1870');
insert into addresses (id, country_iso, city, street, postcode) values (133, 'RU', 'Buturlinovka', '443 Haas Point', '397507');
insert into addresses (id, country_iso, city, street, postcode) values (134, 'CN', 'Jinghai', '0553 Coolidge Place', null);
insert into addresses (id, country_iso, city, street, postcode) values (135, 'HT', 'Abricots', '83 Arizona Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (136, 'ID', 'Cikalong', '75260 Packers Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (137, 'PT', 'Ermelo', '10 Havey Plaza', '4880-128');
insert into addresses (id, country_iso, city, street, postcode) values (138, 'YE', 'Sūq ar Rabū‘', '5021 Vahlen Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (139, 'FR', 'Ivry-sur-Seine', '98 Surrey Lane', '94209 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (140, 'CZ', 'Velké Meziříčí', '7 Lunder Place', '594 01');
insert into addresses (id, country_iso, city, street, postcode) values (141, 'BR', 'Embu', '13112 Transport Court', '06800-000');
insert into addresses (id, country_iso, city, street, postcode) values (142, 'RU', 'Zainsk', '8 Towne Crossing', '423524');
insert into addresses (id, country_iso, city, street, postcode) values (143, 'PH', 'Limanancong', '22 Sommers Drive', '8102');
insert into addresses (id, country_iso, city, street, postcode) values (144, 'FR', 'Perpignan', '8 Lukken Avenue', '66050 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (145, 'PH', 'Sagay', '58 Hoepker Lane', '9103');
insert into addresses (id, country_iso, city, street, postcode) values (146, 'CN', 'Shikeng', '68373 Anthes Junction', null);
insert into addresses (id, country_iso, city, street, postcode) values (147, 'ID', 'Purwojoyo', '91 Bunting Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (148, 'ID', 'Rowokangkung', '90 1st Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (149, 'NZ', 'Papakura', '1167 Morrow Alley', '2113');
insert into addresses (id, country_iso, city, street, postcode) values (150, 'IT', 'Ancona', '797 Thierer Drive', '60129');
insert into addresses (id, country_iso, city, street, postcode) values (151, 'RU', 'Kedrovoye', '7343 Laurel Street', '624088');
insert into addresses (id, country_iso, city, street, postcode) values (152, 'PS', 'Al Midyah', '27 Aberg Drive', null);
insert into addresses (id, country_iso, city, street, postcode) values (153, 'TZ', 'Mgandu', '41561 Chive Park', null);
insert into addresses (id, country_iso, city, street, postcode) values (154, 'ID', 'Jampang Tengah', '52843 Sachs Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (155, 'PT', 'São Tomé', '3256 Swallow Alley', '4795-549');
insert into addresses (id, country_iso, city, street, postcode) values (156, 'CN', 'Cangshan', '71 Shoshone Park', null);
insert into addresses (id, country_iso, city, street, postcode) values (157, 'FR', 'Arcachon', '1 Dakota Trail', '33314 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (158, 'US', 'Omaha', '51033 Parkside Road', '68134');
insert into addresses (id, country_iso, city, street, postcode) values (159, 'PT', 'Baleal', '6 Hudson Hill', '2520-005');
insert into addresses (id, country_iso, city, street, postcode) values (160, 'PK', 'Jahāniān Shāh', '083 Talmadge Terrace', '40231');
insert into addresses (id, country_iso, city, street, postcode) values (161, 'RU', 'Sheregesh', '0806 Sullivan Court', '660126');
insert into addresses (id, country_iso, city, street, postcode) values (162, 'RU', 'Yaroslavl', '63 Elgar Way', '302025');
insert into addresses (id, country_iso, city, street, postcode) values (163, 'PE', 'Sabandia', '12 Doe Crossing Circle', null);
insert into addresses (id, country_iso, city, street, postcode) values (164, 'PL', 'Kamiennik', '97 Drewry Center', '48-388');
insert into addresses (id, country_iso, city, street, postcode) values (165, 'BR', 'Garanhuns', '3449 Claremont Crossing', '55290-000');
insert into addresses (id, country_iso, city, street, postcode) values (166, 'SE', 'Partille', '54 Fisk Terrace', '433 84');
insert into addresses (id, country_iso, city, street, postcode) values (167, 'KR', 'Uijeongbu-si', '8357 Sundown Court', null);
insert into addresses (id, country_iso, city, street, postcode) values (168, 'CO', 'Espinal', '047 Tennessee Junction', '733529');
insert into addresses (id, country_iso, city, street, postcode) values (169, 'VN', 'An Châu', '363 Monica Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (170, 'CN', 'Gongnong', '0683 Melrose Hill', null);
insert into addresses (id, country_iso, city, street, postcode) values (171, 'GB', 'Belfast', '11 Calypso Way', 'BT2');
insert into addresses (id, country_iso, city, street, postcode) values (172, 'BY', 'Vyerkhnyadzvinsk', '85 Springs Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (173, 'CN', 'Taiba', '32 Florence Court', null);
insert into addresses (id, country_iso, city, street, postcode) values (174, 'MX', 'Lazaro Cardenas', '56 Golf View Lane', '69800');
insert into addresses (id, country_iso, city, street, postcode) values (175, 'PH', 'Dumingag', '45 Sutteridge Drive', '7028');
insert into addresses (id, country_iso, city, street, postcode) values (176, 'IR', 'Zahedan', '26577 Magdeline Junction', null);
insert into addresses (id, country_iso, city, street, postcode) values (177, 'CN', 'Baizhang', '253 Dwight Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (178, 'LI', 'Planken', '1089 Derek Road', '9498');
insert into addresses (id, country_iso, city, street, postcode) values (179, 'CN', 'Ganlin', '764 Knutson Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (180, 'ID', 'Karangbungur', '0216 Crescent Oaks Trail', null);
insert into addresses (id, country_iso, city, street, postcode) values (181, 'NG', 'Ilesa', '068 Delladonna Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (182, 'TN', 'Thala', '96145 Shopko Terrace', null);
insert into addresses (id, country_iso, city, street, postcode) values (183, 'PL', 'Olszanica', '35 Chinook Point', '38-722');
insert into addresses (id, country_iso, city, street, postcode) values (184, 'CN', 'Hanyuan', '5 Claremont Junction', null);
insert into addresses (id, country_iso, city, street, postcode) values (185, 'GR', 'Psychikó', '78917 Manitowish Trail', null);
insert into addresses (id, country_iso, city, street, postcode) values (186, 'RU', 'Blagoveshchensk', '6282 Michigan Plaza', '453430');
insert into addresses (id, country_iso, city, street, postcode) values (187, 'AR', 'La Calera', '0 Blue Bill Park Junction', '4158');
insert into addresses (id, country_iso, city, street, postcode) values (188, 'PT', 'Granja', '638 Marquette Terrace', '4690-711');
insert into addresses (id, country_iso, city, street, postcode) values (189, 'TD', 'Faya-Largeau', '2 Sugar Place', null);
insert into addresses (id, country_iso, city, street, postcode) values (190, 'CN', 'Gaotan', '74 Monument Junction', null);
insert into addresses (id, country_iso, city, street, postcode) values (191, 'MX', 'Alvaro Obregon', '1 Twin Pines Point', '29913');
insert into addresses (id, country_iso, city, street, postcode) values (192, 'CN', 'Kutao', '3 Kingsford Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (193, 'PH', 'Magsaysay', '06047 Corben Place', '9221');
insert into addresses (id, country_iso, city, street, postcode) values (194, 'CN', 'Zhoukou', '7 Moose Crossing', null);
insert into addresses (id, country_iso, city, street, postcode) values (195, 'ID', 'Setanggor', '9634 Chinook Park', null);
insert into addresses (id, country_iso, city, street, postcode) values (196, 'CZ', 'Hronov', '826 Kenwood Parkway', '549 31');
insert into addresses (id, country_iso, city, street, postcode) values (197, 'RU', 'Nikolo-Pavlovskoye', '9701 Hoepker Parkway', '622911');
insert into addresses (id, country_iso, city, street, postcode) values (198, 'CN', 'Yong’an', '4948 Westridge Avenue', null);
insert into addresses (id, country_iso, city, street, postcode) values (199, 'ID', 'Rappang', '18 Melody Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (200, 'ID', 'Ciseureuheun', '5353 Gulseth Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (201, 'CN', 'Jiangcheng', '2 Merrick Circle', null);
insert into addresses (id, country_iso, city, street, postcode) values (202, 'CN', 'Huazhuang', '2287 Tomscot Crossing', null);
insert into addresses (id, country_iso, city, street, postcode) values (203, 'CN', 'Hengyang', '4798 Sunnyside Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (204, 'CZ', 'Bechyně', '483 Northridge Way', '391 65');
insert into addresses (id, country_iso, city, street, postcode) values (205, 'PY', 'Pirapo', '245 Shoshone Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (206, 'ET', 'Addiet Canna', '6 Golf View Hill', null);
insert into addresses (id, country_iso, city, street, postcode) values (207, 'CN', 'Shuguang', '778 Knutson Avenue', null);
insert into addresses (id, country_iso, city, street, postcode) values (208, 'OM', 'Bayt al ‘Awābī', '280 Kinsman Drive', null);
insert into addresses (id, country_iso, city, street, postcode) values (209, 'PS', 'Şānūr', '3 Golf View Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (210, 'BG', 'Isperikh', '3297 Vernon Circle', '7447');
insert into addresses (id, country_iso, city, street, postcode) values (211, 'CN', 'Yangying', '4820 Sauthoff Trail', null);
insert into addresses (id, country_iso, city, street, postcode) values (212, 'GE', 'Gudauta', '814 Kim Crossing', null);
insert into addresses (id, country_iso, city, street, postcode) values (213, 'RE', 'Le Tampon', '814 Fairview Road', '97838 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (214, 'CN', 'Yangshan', '3001 Northfield Park', null);
insert into addresses (id, country_iso, city, street, postcode) values (215, 'CN', 'Jiangduo', '79405 Saint Paul Road', null);
insert into addresses (id, country_iso, city, street, postcode) values (216, 'UA', 'Manyava', '42649 Boyd Pass', null);
insert into addresses (id, country_iso, city, street, postcode) values (217, 'PH', 'Palangue', '9 Gale Center', '4110');
insert into addresses (id, country_iso, city, street, postcode) values (218, 'PE', 'Quiñota', '449 Drewry Drive', null);
insert into addresses (id, country_iso, city, street, postcode) values (219, 'CN', 'Hanjia', '8 Holmberg Trail', null);
insert into addresses (id, country_iso, city, street, postcode) values (220, 'FR', 'Rennes', '008 Kim Way', '35009 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (221, 'ID', 'Timba Timuk', '2849 Upham Lane', null);
insert into addresses (id, country_iso, city, street, postcode) values (222, 'BR', 'Pontalina', '94654 Fair Oaks Pass', '75620-000');
insert into addresses (id, country_iso, city, street, postcode) values (223, 'ID', 'Sukatani', '60 1st Crossing', null);
insert into addresses (id, country_iso, city, street, postcode) values (224, 'MR', 'Atar', '4890 Grim Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (225, 'CO', 'Chachagüí', '9132 Riverside Hill', '522007');
insert into addresses (id, country_iso, city, street, postcode) values (226, 'CN', 'Darong', '4 Mcguire Junction', null);
insert into addresses (id, country_iso, city, street, postcode) values (227, 'PL', 'Murowana Goślina', '1379 Magdeline Center', '62-096');
insert into addresses (id, country_iso, city, street, postcode) values (228, 'CN', 'Gyangkar', '6109 Shoshone Crossing', null);
insert into addresses (id, country_iso, city, street, postcode) values (229, 'RU', 'Orekhovo-Zuyevo', '4 Morrow Place', '142609');
insert into addresses (id, country_iso, city, street, postcode) values (230, 'CO', 'Dos Quebradas', '8322 Luster Lane', '661008');
insert into addresses (id, country_iso, city, street, postcode) values (231, 'CN', 'Hengjie', '0 Maple Pass', null);
insert into addresses (id, country_iso, city, street, postcode) values (232, 'FR', 'Lyon', '79 Hauk Junction', '69446 CEDEX 03');
insert into addresses (id, country_iso, city, street, postcode) values (233, 'TH', 'Tha Luang', '5508 Rowland Center', '15130');
insert into addresses (id, country_iso, city, street, postcode) values (234, 'ID', 'Paciran', '40740 Maywood Parkway', null);
insert into addresses (id, country_iso, city, street, postcode) values (235, 'DE', 'Frankfurt am Main', '752 Rieder Center', '60549');
insert into addresses (id, country_iso, city, street, postcode) values (236, 'ID', 'Colendra', '2341 Sloan Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (237, 'CN', 'Xuebu', '52595 Hauk Park', null);
insert into addresses (id, country_iso, city, street, postcode) values (238, 'KR', 'Busan', '7 Lakewood Gardens Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (239, 'CN', 'Xixi', '1763 Springview Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (240, 'PH', 'San Roque', '7550 Calypso Trail', '6415');
insert into addresses (id, country_iso, city, street, postcode) values (241, 'CN', 'Qingyun', '4 Dawn Circle', null);
insert into addresses (id, country_iso, city, street, postcode) values (242, 'DO', 'Cotuí', '011 Schurz Way', '10210');
insert into addresses (id, country_iso, city, street, postcode) values (243, 'LK', 'Ja Ela', '74 Fair Oaks Circle', '11440');
insert into addresses (id, country_iso, city, street, postcode) values (244, 'CN', 'Huangjia', '25 Butterfield Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (245, 'RU', 'Novaya Lyalya', '9434 Blackbird Trail', '624400');
insert into addresses (id, country_iso, city, street, postcode) values (246, 'RU', 'Blagodatnoye', '71 Mariners Cove Crossing', '356503');
insert into addresses (id, country_iso, city, street, postcode) values (247, 'CZ', 'Mýto', '69 Basil Trail', '347 01');
insert into addresses (id, country_iso, city, street, postcode) values (248, 'UZ', 'Yangiyŭl', '8 Marquette Avenue', null);
insert into addresses (id, country_iso, city, street, postcode) values (249, 'JP', 'Miyata', '7 Sunfield Circle', '981-4305');
insert into addresses (id, country_iso, city, street, postcode) values (250, 'JP', 'Hita', '58305 Lakewood Gardens Drive', '419-0125');
insert into addresses (id, country_iso, city, street, postcode) values (251, 'CN', 'Sangba', '9 Dryden Place', null);
insert into addresses (id, country_iso, city, street, postcode) values (252, 'NL', 'Apeldoorn', '557 Division Junction', '7329');
insert into addresses (id, country_iso, city, street, postcode) values (253, 'VE', 'San Francisco', '3654 David Center', null);
insert into addresses (id, country_iso, city, street, postcode) values (254, 'CZ', 'Náklo', '2 Redwing Crossing', '783 32');
insert into addresses (id, country_iso, city, street, postcode) values (255, 'UA', 'Turka', '56385 Kedzie Terrace', null);
insert into addresses (id, country_iso, city, street, postcode) values (256, 'RU', 'Yazykovo', '3454 Montana Point', '453444');
insert into addresses (id, country_iso, city, street, postcode) values (257, 'RU', 'Kirs', '78 Del Mar Lane', '155310');
insert into addresses (id, country_iso, city, street, postcode) values (258, 'TL', 'Venilale', '946 Kingsford Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (259, 'PH', 'Sapang Buho', '2510 Fulton Drive', '5211');
insert into addresses (id, country_iso, city, street, postcode) values (260, 'RU', 'Uren’', '86 Cordelia Place', '606800');
insert into addresses (id, country_iso, city, street, postcode) values (261, 'NO', 'Bodø', '1 Sutteridge Court', '8038');
insert into addresses (id, country_iso, city, street, postcode) values (262, 'PH', 'Kolumbug', '73 Lighthouse Bay Plaza', '2444');
insert into addresses (id, country_iso, city, street, postcode) values (263, 'CN', 'Rongkou', '0 North Park', null);
insert into addresses (id, country_iso, city, street, postcode) values (264, 'TZ', 'Mbinga', '9224 Maple Wood Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (265, 'GR', 'Filótion', '95 Calypso Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (266, 'CN', 'Jinan', '7640 Ronald Regan Trail', null);
insert into addresses (id, country_iso, city, street, postcode) values (267, 'ID', 'Panjerrejo', '0 Harbort Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (268, 'NO', 'Oslo', '1 Memorial Alley', '0773');
insert into addresses (id, country_iso, city, street, postcode) values (269, 'PL', 'Purda', '656 Miller Hill', '11-030');
insert into addresses (id, country_iso, city, street, postcode) values (270, 'GR', 'Erétria', '3070 Hanover Place', null);
insert into addresses (id, country_iso, city, street, postcode) values (271, 'PL', 'Bełchatów', '651 Mesta Park', '97-413');
insert into addresses (id, country_iso, city, street, postcode) values (272, 'ID', 'Halimaung Jaya (F-3)', '0 Continental Court', null);
insert into addresses (id, country_iso, city, street, postcode) values (273, 'GT', 'Zaragoza', '00 Forster Trail', '04015');
insert into addresses (id, country_iso, city, street, postcode) values (274, 'KW', 'Ar Riqqah', '3 Superior Center', null);
insert into addresses (id, country_iso, city, street, postcode) values (275, 'CN', 'Wuhu', '119 Pawling Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (276, 'CZ', 'Velké Meziříčí', '87 Clyde Gallagher Plaza', '594 01');
insert into addresses (id, country_iso, city, street, postcode) values (277, 'RU', 'Tsimlyansk', '03614 Valley Edge Avenue', '347320');
insert into addresses (id, country_iso, city, street, postcode) values (278, 'CZ', 'Žulová', '181 Del Mar Trail', '790 65');
insert into addresses (id, country_iso, city, street, postcode) values (279, 'BR', 'Sousa', '5 Summit Plaza', '58800-000');
insert into addresses (id, country_iso, city, street, postcode) values (280, 'RU', 'Bira', '874 Arrowood Junction', '679130');
insert into addresses (id, country_iso, city, street, postcode) values (281, 'PH', 'Tagapul-an', '337 Commercial Center', '6712');
insert into addresses (id, country_iso, city, street, postcode) values (282, 'CN', 'Linggou', '83 Iowa Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (283, 'ID', 'Dukuhsia', '4508 Main Road', null);
insert into addresses (id, country_iso, city, street, postcode) values (284, 'FR', 'Blois', '504 Prairie Rose Road', '41015 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (285, 'PL', 'Sośnie', '2936 Linden Crossing', '63-435');
insert into addresses (id, country_iso, city, street, postcode) values (286, 'PA', 'Los Lotes', '2868 Susan Junction', null);
insert into addresses (id, country_iso, city, street, postcode) values (287, 'CN', 'Luoqiao', '198 Sullivan Pass', null);
insert into addresses (id, country_iso, city, street, postcode) values (288, 'FR', 'Landivisiau', '47 Crowley Avenue', '29404 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (289, 'PH', 'Alimono', '1693 Lukken Trail', '7005');
insert into addresses (id, country_iso, city, street, postcode) values (290, 'FR', 'Dinan', '344 Little Fleur Court', '22104 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (291, 'CO', 'Mistrató', '0374 Bay Junction', '664028');
insert into addresses (id, country_iso, city, street, postcode) values (292, 'PS', 'Ḩuwwārah', '21 Valley Edge Crossing', null);
insert into addresses (id, country_iso, city, street, postcode) values (293, 'US', 'Kansas City', '99 Gulseth Hill', '64130');
insert into addresses (id, country_iso, city, street, postcode) values (294, 'US', 'Lansing', '47465 Dovetail Pass', '48919');
insert into addresses (id, country_iso, city, street, postcode) values (295, 'GR', 'Néa Manolás', '72 Pleasure Court', null);
insert into addresses (id, country_iso, city, street, postcode) values (296, 'TN', 'El Fahs', '84434 Beilfuss Pass', null);
insert into addresses (id, country_iso, city, street, postcode) values (297, 'YE', 'Māwiyah', '92 Fallview Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (298, 'CA', 'Labrador City', '8964 Johnson Terrace', 'A2V');
insert into addresses (id, country_iso, city, street, postcode) values (299, 'CN', 'Gyamco', '6 Anhalt Lane', null);
insert into addresses (id, country_iso, city, street, postcode) values (300, 'PY', 'Itauguá', '71548 Kipling Road', null);
insert into addresses (id, country_iso, city, street, postcode) values (301, 'CN', 'Jun’an', '86 Lotheville Center', null);
insert into addresses (id, country_iso, city, street, postcode) values (302, 'NO', 'Fauske', '093 Hayes Crossing', '8206');
insert into addresses (id, country_iso, city, street, postcode) values (303, 'ID', 'Sakerta Timur', '209 Kipling Center', null);
insert into addresses (id, country_iso, city, street, postcode) values (304, 'ID', 'Lokokrangan', '3995 Schmedeman Hill', null);
insert into addresses (id, country_iso, city, street, postcode) values (305, 'FI', 'Haukipudas', '21847 Union Center', '90840');
insert into addresses (id, country_iso, city, street, postcode) values (306, 'ID', 'Ngadipuro', '68190 Lerdahl Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (307, 'US', 'Shawnee Mission', '5137 Sachs Place', '66225');
insert into addresses (id, country_iso, city, street, postcode) values (308, 'CN', 'Heishui', '4653 Parkside Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (309, 'CN', 'Baizhang', '1 5th Avenue', null);
insert into addresses (id, country_iso, city, street, postcode) values (310, 'US', 'Springfield', '13 Melvin Point', '01114');
insert into addresses (id, country_iso, city, street, postcode) values (311, 'TH', 'Lom Sak', '363 Kropf Street', '67110');
insert into addresses (id, country_iso, city, street, postcode) values (312, 'FR', 'Caen', '4984 Larry Street', '14030 CEDEX 4');
insert into addresses (id, country_iso, city, street, postcode) values (313, 'PL', 'Pilawa', '1 Browning Street', '08-440');
insert into addresses (id, country_iso, city, street, postcode) values (314, 'PY', 'San Juan Bautista', '2092 Kensington Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (315, 'FR', 'Lille', '18126 Bunker Hill Lane', '59044 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (316, 'PH', 'Limbuhan', '9 Hansons Plaza', '7203');
insert into addresses (id, country_iso, city, street, postcode) values (317, 'MX', 'San Sebastian', '485 Mandrake Hill', '69200');
insert into addresses (id, country_iso, city, street, postcode) values (318, 'PH', 'Apurawan', '3 Dorton Point', '8717');
insert into addresses (id, country_iso, city, street, postcode) values (319, 'PH', 'Adela', '55 Sunfield Circle', '3332');
insert into addresses (id, country_iso, city, street, postcode) values (320, 'RU', 'Pechersk', '809 Lotheville Circle', '216134');
insert into addresses (id, country_iso, city, street, postcode) values (321, 'CN', 'Dalu', '1 Main Trail', null);
insert into addresses (id, country_iso, city, street, postcode) values (322, 'NG', 'Sapele', '6 High Crossing Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (323, 'ID', 'Krajan Dermawuharjo', '51 Roth Park', null);
insert into addresses (id, country_iso, city, street, postcode) values (324, 'CN', 'Yuanqiao', '2952 Norway Maple Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (325, 'AR', 'Libertad', '0192 Armistice Street', '3374');
insert into addresses (id, country_iso, city, street, postcode) values (326, 'UA', 'Obertyn', '8154 Shasta Trail', null);
insert into addresses (id, country_iso, city, street, postcode) values (327, 'JP', 'Nobeoka', '02523 Reinke Trail', '882-0877');
insert into addresses (id, country_iso, city, street, postcode) values (328, 'FM', 'Lamotrek', '70 Nelson Pass', null);
insert into addresses (id, country_iso, city, street, postcode) values (329, 'US', 'Rochester', '88097 Menomonie Alley', '14652');
insert into addresses (id, country_iso, city, street, postcode) values (330, 'CN', 'Ketian', '3 Orin Court', null);
insert into addresses (id, country_iso, city, street, postcode) values (331, 'CN', 'Qingjiangqiao', '8 Surrey Hill', null);
insert into addresses (id, country_iso, city, street, postcode) values (332, 'RU', 'Kudara-Somon', '8 Fisk Way', '671836');
insert into addresses (id, country_iso, city, street, postcode) values (333, 'BA', 'Popovi', '58 Karstens Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (334, 'CA', 'Sainte-Anne-des-Monts', '3 Hagan Point', 'L8P');
insert into addresses (id, country_iso, city, street, postcode) values (335, 'NG', 'Kontagora', '727 Melby Park', null);
insert into addresses (id, country_iso, city, street, postcode) values (336, 'CN', 'Tianyu', '0 Vidon Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (337, 'HN', 'Quebradas', '6 Springview Road', null);
insert into addresses (id, country_iso, city, street, postcode) values (338, 'EG', 'Kafr Şaqr', '50 Becker Center', null);
insert into addresses (id, country_iso, city, street, postcode) values (339, 'BR', 'Paranaíba', '7191 Lukken Junction', '79500-000');
insert into addresses (id, country_iso, city, street, postcode) values (340, 'TN', 'Al Qarmadah', '6043 Vermont Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (341, 'FI', 'Viitasaari', '2356 Huxley Road', '44501');
insert into addresses (id, country_iso, city, street, postcode) values (342, 'PH', 'Camaligan', '17 Kings Court', '4401');
insert into addresses (id, country_iso, city, street, postcode) values (343, 'RU', 'Lysogorskaya', '5 Gateway Street', '357838');
insert into addresses (id, country_iso, city, street, postcode) values (344, 'MG', 'Antanifotsy', '3000 Bartelt Parkway', null);
insert into addresses (id, country_iso, city, street, postcode) values (345, 'GL', 'Upernavik', '47887 Judy Lane', '3962');
insert into addresses (id, country_iso, city, street, postcode) values (346, 'ID', 'Sadang Kulon', '246 Gale Trail', null);
insert into addresses (id, country_iso, city, street, postcode) values (347, 'TN', 'Nabeul', '9050 Crownhardt Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (348, 'ID', 'Cikawunggading', '847 Jenna Circle', null);
insert into addresses (id, country_iso, city, street, postcode) values (349, 'PT', 'Azinhal', '13 Rutledge Drive', '8950-023');
insert into addresses (id, country_iso, city, street, postcode) values (350, 'RU', 'Zavetnoye', '83925 Sheridan Avenue', '357014');
insert into addresses (id, country_iso, city, street, postcode) values (351, 'DE', 'München', '680 Clemons Circle', '81373');
insert into addresses (id, country_iso, city, street, postcode) values (352, 'FR', 'Saint-Jean-de-Védas', '31881 Londonderry Hill', '34435 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (353, 'JM', 'Bluefields', '8149 Division Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (354, 'UA', 'Nyzhni Petrivtsi', '88 Northwestern Junction', null);
insert into addresses (id, country_iso, city, street, postcode) values (355, 'PH', 'San Jose', '19 Gulseth Lane', '8427');
insert into addresses (id, country_iso, city, street, postcode) values (356, 'SE', 'Partille', '5 Dexter Plaza', '433 31');
insert into addresses (id, country_iso, city, street, postcode) values (357, 'FR', 'Le Mans', '7439 Mallory Plaza', '72100');
insert into addresses (id, country_iso, city, street, postcode) values (358, 'ID', 'Banjar Penyalin', '5198 Lakewood Gardens Hill', null);
insert into addresses (id, country_iso, city, street, postcode) values (359, 'FR', 'Villeneuve-la-Garenne', '392 Springs Circle', '92393 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (360, 'GU', 'Agana Heights Village', '04436 Katie Drive', '96929');
insert into addresses (id, country_iso, city, street, postcode) values (361, 'CN', 'Zhenxi', '41839 Eggendart Lane', null);
insert into addresses (id, country_iso, city, street, postcode) values (362, 'KR', 'Heung-hai', '035 Hazelcrest Hill', null);
insert into addresses (id, country_iso, city, street, postcode) values (363, 'TN', 'Douane', '247 Ridge Oak Court', null);
insert into addresses (id, country_iso, city, street, postcode) values (364, 'CN', 'Zhangqing', '743 David Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (365, 'JP', 'Takikawa', '7 Killdeer Drive', '503-0625');
insert into addresses (id, country_iso, city, street, postcode) values (366, 'CA', 'La Tuque', '7490 Mockingbird Drive', 'G9X');
insert into addresses (id, country_iso, city, street, postcode) values (367, 'PH', 'Baclayon', '41259 Crownhardt Avenue', '6301');
insert into addresses (id, country_iso, city, street, postcode) values (368, 'CN', 'Haliut', '6 Ohio Terrace', null);
insert into addresses (id, country_iso, city, street, postcode) values (369, 'ID', 'Jasugih Selatan', '5 Algoma Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (370, 'CO', 'Barbosa', '6863 Bunker Hill Junction', '684517');
insert into addresses (id, country_iso, city, street, postcode) values (371, 'NA', 'Aranos', '31067 Farragut Park', null);
insert into addresses (id, country_iso, city, street, postcode) values (372, 'GM', 'Abuko', '66 Division Lane', null);
insert into addresses (id, country_iso, city, street, postcode) values (373, 'ID', 'Peuhaq', '3 Arkansas Parkway', null);
insert into addresses (id, country_iso, city, street, postcode) values (374, 'PH', 'Sabang', '4127 Acker Road', '5203');
insert into addresses (id, country_iso, city, street, postcode) values (375, 'CN', 'Haozhai', '5 Morningstar Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (376, 'BR', 'Indaial', '33 Duke Lane', '89130-000');
insert into addresses (id, country_iso, city, street, postcode) values (377, 'ID', 'Bulangan', '1 Old Gate Pass', null);
insert into addresses (id, country_iso, city, street, postcode) values (378, 'CN', 'Yengiawat', '882 Nelson Pass', null);
insert into addresses (id, country_iso, city, street, postcode) values (379, 'CN', 'Anshun', '62238 Mayfield Terrace', null);
insert into addresses (id, country_iso, city, street, postcode) values (380, 'US', 'Midland', '87078 Forster Trail', '79705');
insert into addresses (id, country_iso, city, street, postcode) values (381, 'ID', 'Weekombaka', '0 Kensington Hill', null);
insert into addresses (id, country_iso, city, street, postcode) values (382, 'CZ', 'Štítina', '6809 Stang Avenue', '747 91');
insert into addresses (id, country_iso, city, street, postcode) values (383, 'AR', 'Pampa de los Guanacos', '517 Fair Oaks Hill', '3181');
insert into addresses (id, country_iso, city, street, postcode) values (384, 'NG', 'Malummaduri', '0 Corry Junction', null);
insert into addresses (id, country_iso, city, street, postcode) values (385, 'BG', 'Chelopech', '5843 Walton Terrace', '2087');
insert into addresses (id, country_iso, city, street, postcode) values (386, 'US', 'Orange', '488 Monica Lane', '92668');
insert into addresses (id, country_iso, city, street, postcode) values (387, 'IE', 'Raphoe', '10 Columbus Circle', 'X91');
insert into addresses (id, country_iso, city, street, postcode) values (388, 'PH', 'Bagacay', '424 Moland Point', '1427');
insert into addresses (id, country_iso, city, street, postcode) values (389, 'CN', 'Changqing', '147 Jackson Park', null);
insert into addresses (id, country_iso, city, street, postcode) values (390, 'ET', 'Lobuni', '3 Spaight Avenue', null);
insert into addresses (id, country_iso, city, street, postcode) values (391, 'DO', 'Rincón', '8 Northport Court', '10602');
insert into addresses (id, country_iso, city, street, postcode) values (392, 'TH', 'Bueng Kum', '7 Prairieview Center', '10240');
insert into addresses (id, country_iso, city, street, postcode) values (393, 'CN', 'Tanxi', '992 Bayside Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (394, 'PL', 'Stopnica', '05953 Sunbrook Plaza', '28-130');
insert into addresses (id, country_iso, city, street, postcode) values (395, 'ID', 'Pinara', '2 Onsgard Center', null);
insert into addresses (id, country_iso, city, street, postcode) values (396, 'CM', 'Batouri', '503 Buell Center', null);
insert into addresses (id, country_iso, city, street, postcode) values (397, 'ID', 'Oli', '5530 Forest Dale Avenue', null);
insert into addresses (id, country_iso, city, street, postcode) values (398, 'US', 'Minneapolis', '36716 Bartelt Way', '55446');
insert into addresses (id, country_iso, city, street, postcode) values (399, 'RU', 'Bogovarovo', '0545 Messerschmidt Circle', '157780');
insert into addresses (id, country_iso, city, street, postcode) values (400, 'CN', 'Huliao', '389 Pennsylvania Junction', null);
insert into addresses (id, country_iso, city, street, postcode) values (401, 'CN', 'Lanyang', '16401 Alpine Road', null);
insert into addresses (id, country_iso, city, street, postcode) values (402, 'ID', 'Kalapagada', '1475 Brickson Park Place', null);
insert into addresses (id, country_iso, city, street, postcode) values (403, 'GT', 'Mixco', '11666 Milwaukee Lane', '01057');
insert into addresses (id, country_iso, city, street, postcode) values (404, 'PH', 'Lapi', '6 Novick Plaza', '5307');
insert into addresses (id, country_iso, city, street, postcode) values (405, 'RU', 'Drakino', '3174 Emmet Street', '397943');
insert into addresses (id, country_iso, city, street, postcode) values (406, 'PH', 'Umanday Centro', '76461 Golf View Parkway', '2415');
insert into addresses (id, country_iso, city, street, postcode) values (407, 'CN', 'Yuguan', '2 Russell Drive', null);
insert into addresses (id, country_iso, city, street, postcode) values (408, 'YE', 'Jawl al Majma‘', '5985 Lillian Place', null);
insert into addresses (id, country_iso, city, street, postcode) values (409, 'JP', 'Sakai', '6 Talmadge Alley', '999-2256');
insert into addresses (id, country_iso, city, street, postcode) values (410, 'JP', 'Saijō', '1580 Del Sol Lane', '793-0213');
insert into addresses (id, country_iso, city, street, postcode) values (411, 'PL', 'Czerwionka-Leszczyny', '0710 American Hill', '44-238');
insert into addresses (id, country_iso, city, street, postcode) values (412, 'MG', 'Bealanana', '85169 Sauthoff Place', null);
insert into addresses (id, country_iso, city, street, postcode) values (413, 'ES', 'Zamora', '1 Prairie Rose Park', '49003');
insert into addresses (id, country_iso, city, street, postcode) values (414, 'CN', 'Wu’erqihan', '80945 Lindbergh Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (415, 'ID', 'Tanggul Wetan', '73 Farragut Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (416, 'US', 'Pensacola', '97876 Arizona Court', '32595');
insert into addresses (id, country_iso, city, street, postcode) values (417, 'CN', 'Beiyang', '81 Anthes Parkway', null);
insert into addresses (id, country_iso, city, street, postcode) values (418, 'AR', 'Libertad', '13516 Mayer Point', '3374');
insert into addresses (id, country_iso, city, street, postcode) values (419, 'BG', 'Dimovo', '9087 Artisan Crossing', '3759');
insert into addresses (id, country_iso, city, street, postcode) values (420, 'CN', 'Donghai', '92717 Memorial Junction', null);
insert into addresses (id, country_iso, city, street, postcode) values (421, 'LT', 'Kelmė', '01 Bayside Place', '86001');
insert into addresses (id, country_iso, city, street, postcode) values (422, 'FR', 'Saint-Jouan-des-Guérets', '4 Sugar Lane', '35435 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (423, 'CU', 'Santa Clara', '62084 Pearson Drive', null);
insert into addresses (id, country_iso, city, street, postcode) values (424, 'FR', 'Champagnole', '11 Dennis Way', '39304 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (425, 'ID', 'Palamadu', '37 Westerfield Lane', null);
insert into addresses (id, country_iso, city, street, postcode) values (426, 'PH', 'Calauag', '573 Lyons Circle', '4318');
insert into addresses (id, country_iso, city, street, postcode) values (427, 'UA', 'Zhovkva', '79 Cherokee Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (428, 'NG', 'Jikamshi', '12491 Union Drive', null);
insert into addresses (id, country_iso, city, street, postcode) values (429, 'ID', 'Negararatu', '1 Southridge Circle', null);
insert into addresses (id, country_iso, city, street, postcode) values (430, 'TH', 'Soeng Sang', '0850 Texas Crossing', '30330');
insert into addresses (id, country_iso, city, street, postcode) values (431, 'CN', 'Yunmeng Chengguanzhen', '6974 Golf View Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (432, 'CZ', 'Včelná', '65 Hauk Place', '373 82');
insert into addresses (id, country_iso, city, street, postcode) values (433, 'CN', 'Wanjiazhuang', '13 Bunker Hill Road', null);
insert into addresses (id, country_iso, city, street, postcode) values (434, 'MU', 'Cap Malheureux', '86 Kenwood Circle', null);
insert into addresses (id, country_iso, city, street, postcode) values (435, 'UA', 'Ripky', '56 Del Sol Lane', null);
insert into addresses (id, country_iso, city, street, postcode) values (436, 'MV', 'Dhidhdhoo', '58083 Fordem Lane', null);
insert into addresses (id, country_iso, city, street, postcode) values (437, 'AR', 'Palpalá', '57 Dottie Avenue', '4612');
insert into addresses (id, country_iso, city, street, postcode) values (438, 'VN', 'Yên Bái', '6229 Eggendart Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (439, 'UA', 'Manevychi', '761 Cottonwood Place', null);
insert into addresses (id, country_iso, city, street, postcode) values (440, 'CN', 'Xiangshan', '2 Lien Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (441, 'SE', 'Örnsköldsvik', '37181 Moland Plaza', '891 41');
insert into addresses (id, country_iso, city, street, postcode) values (442, 'PT', 'Escola', '52866 Sheridan Park', '4600-730');
insert into addresses (id, country_iso, city, street, postcode) values (443, 'PY', 'San José', '479 Summit Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (444, 'BA', 'Ljubuški', '59 Cordelia Crossing', null);
insert into addresses (id, country_iso, city, street, postcode) values (445, 'SE', 'Göteborg', '0 Kingsford Circle', '400 15');
insert into addresses (id, country_iso, city, street, postcode) values (446, 'TH', 'Chiang Yuen', '01 Melody Street', '44160');
insert into addresses (id, country_iso, city, street, postcode) values (447, 'FR', 'Besançon', '1337 Blue Bill Park Junction', '25071 CEDEX 9');
insert into addresses (id, country_iso, city, street, postcode) values (448, 'BY', 'Aktsyabrski', '8283 Esker Parkway', null);
insert into addresses (id, country_iso, city, street, postcode) values (449, 'PH', 'San Luis', '04927 North Road', '8511');
insert into addresses (id, country_iso, city, street, postcode) values (450, 'FR', 'Marne-la-Vallée', '5053 Northwestern Street', '77453 CEDEX 2');
insert into addresses (id, country_iso, city, street, postcode) values (451, 'WS', 'Gataivai', '061 4th Alley', null);
insert into addresses (id, country_iso, city, street, postcode) values (452, 'JM', 'Ewarton', '0532 Glendale Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (453, 'PH', 'Cagdianao', '517 Heffernan Terrace', '8411');
insert into addresses (id, country_iso, city, street, postcode) values (454, 'GT', 'Mataquescuintla', '9 Emmet Trail', '06005');
insert into addresses (id, country_iso, city, street, postcode) values (455, 'LB', 'Marjayoûn', '967 Toban Road', null);
insert into addresses (id, country_iso, city, street, postcode) values (456, 'DO', 'Bajos de Haina', '78 Graedel Alley', '11117');
insert into addresses (id, country_iso, city, street, postcode) values (457, 'PT', 'Gondomar', '19961 Havey Hill', '4800-198');
insert into addresses (id, country_iso, city, street, postcode) values (458, 'VN', 'Tân Việt', '76434 Ryan Lane', null);
insert into addresses (id, country_iso, city, street, postcode) values (459, 'FI', 'Särkisalo', '9 Nevada Crossing', '25630');
insert into addresses (id, country_iso, city, street, postcode) values (460, 'CN', 'Zhangcun', '79648 Blue Bill Park Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (461, 'PE', 'Checca', '7326 Arkansas Terrace', null);
insert into addresses (id, country_iso, city, street, postcode) values (462, 'PH', 'Pawa', '65 Anniversary Terrace', '4501');
insert into addresses (id, country_iso, city, street, postcode) values (463, 'KZ', 'Arys', '425 Sycamore Park', null);
insert into addresses (id, country_iso, city, street, postcode) values (464, 'AR', 'Fraile Pintado', '191 Shasta Place', '4506');
insert into addresses (id, country_iso, city, street, postcode) values (465, 'ID', 'Orong', '503 Delaware Point', null);
insert into addresses (id, country_iso, city, street, postcode) values (466, 'RU', 'Verkhneye Kazanishche', '27873 Novick Plaza', '368206');
insert into addresses (id, country_iso, city, street, postcode) values (467, 'JP', 'Hitachi', '225 Spenser Park', '319-1417');
insert into addresses (id, country_iso, city, street, postcode) values (468, 'KR', 'Moppo', '62 Cottonwood Center', null);
insert into addresses (id, country_iso, city, street, postcode) values (469, 'EE', 'Tartu', '258 Bonner Center', null);
insert into addresses (id, country_iso, city, street, postcode) values (470, 'ZM', 'Kataba', '926 Brentwood Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (471, 'SO', 'Dujuuma', '5 Green Ridge Lane', null);
insert into addresses (id, country_iso, city, street, postcode) values (472, 'GR', 'Palaió Fáliro', '2 Pearson Plaza', null);
insert into addresses (id, country_iso, city, street, postcode) values (473, 'SE', 'Finspång', '4 Cambridge Junction', '612 80');
insert into addresses (id, country_iso, city, street, postcode) values (474, 'CN', 'Heshui', '00711 7th Avenue', null);
insert into addresses (id, country_iso, city, street, postcode) values (475, 'CN', 'Magutian', '97834 Rusk Junction', null);
insert into addresses (id, country_iso, city, street, postcode) values (476, 'ID', 'Suruhan', '8 Badeau Way', null);
insert into addresses (id, country_iso, city, street, postcode) values (477, 'VN', 'Quảng Ngãi', '75983 North Pass', null);
insert into addresses (id, country_iso, city, street, postcode) values (478, 'FR', 'Armentières', '2 Sherman Terrace', '59425 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (479, 'CN', 'Zhangshi', '96988 Sycamore Circle', null);
insert into addresses (id, country_iso, city, street, postcode) values (480, 'CN', 'Meilin', '59453 Nobel Terrace', null);
insert into addresses (id, country_iso, city, street, postcode) values (481, 'ID', 'Jampang Tengah', '28561 Warner Lane', null);
insert into addresses (id, country_iso, city, street, postcode) values (482, 'AL', 'Suç', '6 Mccormick Street', null);
insert into addresses (id, country_iso, city, street, postcode) values (483, 'ID', 'Jugantang', '5660 Fremont Place', null);
insert into addresses (id, country_iso, city, street, postcode) values (484, 'BR', 'Santa Quitéria', '97 Northwestern Pass', '62280-000');
insert into addresses (id, country_iso, city, street, postcode) values (485, 'PH', 'Takub', '5177 Mandrake Circle', '6700');
insert into addresses (id, country_iso, city, street, postcode) values (486, 'ID', 'Narukan', '14 Talisman Hill', null);
insert into addresses (id, country_iso, city, street, postcode) values (487, 'BR', 'Criciúma', '22363 Bowman Court', '88800-000');
insert into addresses (id, country_iso, city, street, postcode) values (488, 'CN', 'Shuibian', '68 5th Drive', null);
insert into addresses (id, country_iso, city, street, postcode) values (489, 'VN', 'Vạn Giã', '1899 Scott Park', null);
insert into addresses (id, country_iso, city, street, postcode) values (490, 'KZ', 'Balpyk Bī', '53595 Superior Avenue', null);
insert into addresses (id, country_iso, city, street, postcode) values (491, 'CN', 'Beigang', '5 Schmedeman Drive', null);
insert into addresses (id, country_iso, city, street, postcode) values (492, 'ID', 'Prioso Barat', '1317 Corscot Terrace', null);
insert into addresses (id, country_iso, city, street, postcode) values (493, 'JP', 'Tarumizu', '748 Macpherson Terrace', '861-0133');
insert into addresses (id, country_iso, city, street, postcode) values (494, 'FR', 'Brie-Comte-Robert', '44348 Hovde Pass', '77254 CEDEX');
insert into addresses (id, country_iso, city, street, postcode) values (495, 'CN', 'Bohai', '424 Elka Court', null);
insert into addresses (id, country_iso, city, street, postcode) values (496, 'PL', 'Unisław', '5272 Ramsey Point', '86-260');
insert into addresses (id, country_iso, city, street, postcode) values (497, 'US', 'Tempe', '8 Gateway Drive', '85284');
insert into addresses (id, country_iso, city, street, postcode) values (498, 'ID', 'Sidamukti', '45565 Stone Corner Pass', null);
insert into addresses (id, country_iso, city, street, postcode) values (499, 'KE', 'Karuri', '13857 Tony Drive', null);
insert into addresses (id, country_iso, city, street, postcode) values (500, 'UA', 'Chornobay', '0761 Lillian Plaza', null);
